"""add module icon column

Revision ID: 2eb79fad79aa
Revises: c61a2b91ec27
Create Date: 2026-05-10 09:53:09.483983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb79fad79aa'
down_revision: Union[str, None] = 'c61a2b91ec27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('icon', sa.String(length=10), server_default='📚', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'icon')
    # ### end Alembic commands ###
