"""add generated content table

Revision ID: 717a7cbfbd00
Revises: 933c739968ec
Create Date: 2026-05-12 21:35:03.790601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '717a7cbfbd00'
down_revision: Union[str, None] = '933c739968ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('concept', sa.String(length=200), nullable=False),
    sa.Column('content_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'concept', 'model_used', name='uq_generated_content_lesson_concept_model')
    )
    op.create_index(op.f('ix_generated_content_lesson_id'), 'generated_content', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_content_lesson_id'), table_name='generated_content')
    op.drop_table('generated_content')
    # ### end Alembic commands ###
