"""add skill profile tables

Revision ID: 933c739968ec
Revises: 2eb79fad79aa
Create Date: 2026-05-12 21:20:02.351134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933c739968ec'
down_revision: Union[str, None] = '2eb79fad79aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_mastery',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('quizzes_attempted', sa.Integer(), nullable=False),
    sa.Column('quizzes_correct', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic'),
    sa.UniqueConstraint('user_id', 'topic', name='uq_topic_mastery_user_topic')
    )
    op.create_table('weak_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('concept', sa.String(length=200), nullable=False),
    sa.Column('times_wrong', sa.Integer(), nullable=False),
    sa.Column('times_reinforced', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weak_concepts_user_id'), 'weak_concepts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weak_concepts_user_id'), table_name='weak_concepts')
    op.drop_table('weak_concepts')
    op.drop_table('topic_mastery')
    # ### end Alembic commands ###
