"""index lesson_completion completed_at

Revision ID: 95b2a10479b9
Revises: cdef3b275270
Create Date: 2026-04-25 10:24:04.341791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b2a10479b9'
down_revision: Union[str, None] = 'cdef3b275270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lesson_completions_completed_at'), 'lesson_completions', ['completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_completions_completed_at'), table_name='lesson_completions')
    # ### end Alembic commands ###
