"""add module prerequisites and age range

Revision ID: 9b7815c040
Revises: 5b9ed6eec8c9
Create Date: 2026-05-22 22:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9b7815c040'
down_revision: Union[str, None] = '5b9ed6eec8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('prerequisite_ids', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), server_default='{}', nullable=False))
    op.add_column('modules', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('modules', sa.Column('max_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'max_age')
    op.drop_column('modules', 'min_age')
    op.drop_column('modules', 'prerequisite_ids')
    # ### end Alembic commands ###
