"""parental consent: users columns + one_time_tokens + sent_emails

Revision ID: c61a2b91ec27
Revises: 95b2a10479b9
Create Date: 2026-04-25 21:57:46.238128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61a2b91ec27'
down_revision: Union[str, None] = '95b2a10479b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_time_tokens_jti'), 'one_time_tokens', ['jti'], unique=True)
    op.create_table('sent_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_emails_to_email'), 'sent_emails', ['to_email'], unique=False)
    op.add_column('users', sa.Column('consent_declined_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'deletion_requested_at')
    op.drop_column('users', 'consent_declined_at')
    op.drop_index(op.f('ix_sent_emails_to_email'), table_name='sent_emails')
    op.drop_table('sent_emails')
    op.drop_index(op.f('ix_one_time_tokens_jti'), table_name='one_time_tokens')
    op.drop_table('one_time_tokens')
    # ### end Alembic commands ###
