"""add unique (user_id, lesson_id) to lesson_completions

Revision ID: cdef3b275270
Revises: 35979103ffb9
Create Date: 2026-04-24 19:27:50.441136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdef3b275270'
down_revision: Union[str, None] = '35979103ffb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lesson_completion_user_lesson', 'lesson_completions', ['user_id', 'lesson_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lesson_completion_user_lesson', 'lesson_completions', type_='unique')
    # ### end Alembic commands ###
